cPanel & WHM Locales
====================

These files contain the locale strings for use with cPanel & WHM.  Within the 
data directory, the en.yaml files contain the English strings. Additional .yaml
files in the data directory contain translations provided by cPanel.

The community-locales directory is for storing translations provided by the
community of cPanel & WHM users. Please issue pull requests agaisnt this
directory for new locales.

Providing access to our strings on github accomplishes several goals:

  1. Community translators can easily see which strings changed between
  versions of cPanel & WHM.
  2. It allows people who speak languages that we (cPanel) don't provide
  an opportunity to benefit from the community's efforts.
  3. Community translators have a means of both reporting bugs, and
  providing fixes, in the translations

We would be happy to accept pull requests on this repository, and will try to
get to them as soon as possible.  If it takes us more than a week, please poke
*https://github.com/bk2204[@bk2204]* and he'll review your changes or make sure
someone else does.

Caveat about Community Locales
------------------------------

cPanel is unable to make any guarantees about the quality of community provided
locales. Use them at your own risk.

Data Format
-----------

The files are YAML files that contain a mapping of strings to strings.  The
English string is the key, and the translation is the value.  If the value is an
empty string, the key will be used.  The special +__VERSION+ key must be present
in order for the locale to function.

The strings are in UTF-8 and formatted with Locale::Maketext.  They must not
contain the ASCII apostrophe (decimal 39), ASCII double quote (decimal 34),
ampersand, or less than or greater than signs, as these may result in corrupt
HTML and JSON.  For quotation marks, please use the Unicode quotation marks
corresponding to your locale.  For the other characters, use the
+[output,chr,60]+ notation, or within bracket notation, the chr() notation (e.g.
+[asis,cPanel chr(38) WHM]+).

The strings must not contain HTML or JavaScript.  They are sorted by key for
easy diffing.

For some basics on writing in the Maktext format, please read:
http://docs.cpanel.net/twiki/bin/view/CpanelLocale/BracketNotation