cPanel & WHM Locales
====================

These files contain the locale strings for cPanel & WHM.  Within the data
directory, the en.yaml files contain the English strings, and additional .yaml
files are community-provided translations.

This allows customers and community members who would like to have an early
opportunity to translate cPanel & WHM to do so.  It also allows people who speak
languages that we (cPanel) don't provide to have an opportunity to benefit from
the community's efforts.  But because these are community efforts, we can't
guarantee that they're accurate.

We would be happy to accept pull requests on this repository, and will try to
get to them as soon as possible.  If it takes us more than a week, please poke
*https://github.com/bk2204[@bk2204]* and he'll review your changes or make sure
someone else does.

Data Format
-----------

The files are YAML files that contain a mapping of strings to strings.  The
English string is the key, and the translation is the value.  If the value is an
empty string, the key will be used.  The special +__VERSION+ key must be present
in order for the locale to function.

The strings are in UTF-8 and formatted with Locale::Maketext.  They must not
contain the ASCII apostrophe (decimal 39), ASCII double quote (decimal 34),
ampersand, or less than or greater than signs, as these may result in corrupt
HTML and JSON.  For quotation marks, please use the Unicode quotation marks
corresponding to your locale.  For the other characters, use the
+[output,chr,60]+ notation, or within bracket notation, the chr() notation (e.g.
+[asis,cPanel chr(38) WHM]+).

The strings must not contain HTML or JavaScript.  They are sorted by key for
easy diffing.

Differences between Files
-------------------------

The set of strings can vary between the files.

If the English (+en.yaml+) file contains a string, but another locale does not,
that indicates that no translation exists yet for that string in that locale.
Usually, that means that the string is new or recently changed, and no
translation was available at the time.  Translations will be added as we get
them, but you can also submit pull requests to fill them in.

If a non-English locale contains a string, but the English text does not, that
usually indicates that the string is from an older version of cPanel & WHM and
was translated, but is no longer used in the latest version.  Other than
slightly increasing the size of the compiled locale databases, these strings are
harmless, although they may be removed in future versions.

Note that the +en.yaml+ file in the repository is a combination of the +en.yaml+
and +queue/pending.yaml+ files distributed with cPanel & WHM.  The latter file
is a historical artifact, and the two have been combined here for ease of use.

Error Messages
--------------

By its very nature, this repository contains almost all the error messages that
cPanel & WHM produces.  If you came here because you're looking for support,
please see https://cpanel.com/support/[our support page] for information on how
to open a ticket and access our forums.
